plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.owasp.dependencycheck' version '12.2.2'
	id 'org.sonarqube' version '6.2.0.5505'
	id 'jacoco'
}

group = 'com.devopsproject'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

def internalRepoUrl = providers.gradleProperty("internalRepoUrl")
        .orElse(providers.environmentVariable("INTERNAL_REPO_URL"))
        .getOrElse(null)

if (!internalRepoUrl) {
    throw new GradleException(
            "Internal repository URL is missing. " +
            "Set internalRepoUrl in Gradle properties or INTERNAL_REPO_URL."
    )
}

repositories {
    maven {
        url = uri(internalRepoUrl)
    }

    mavenCentral()
}

dependencies {
    implementation 'com.devopsproject:company-common-lib:1.0.0'

	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyCheck {
    failBuildOnCVSS = 7.0

    nvd {
        apiKey = System.getenv("NVD_API_KEY")
    }
}


tasks.named('test') {
	useJUnitPlatform()
}

sonar {
    properties {
        property "sonar.projectKey", "avi6650_devops-app"
        property "sonar.organization", "avi6650"
        property "sonar.host.url", "https://sonarcloud.io"
    }
}

jacocoTestReport {
    dependsOn test

    reports {
        xml.required = true
        html.required = true
    }
}