apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-app-eks
  region: ca-central-1
  version: "1.36"

vpc:
  nat:
    gateway: Disable

managedNodeGroups:
  - name: devops-app-nodes
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 20
    privateNetworking: false